---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodereaper
  namespace: kube-system
  labels:
    app: nodereaper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodereaper
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodereaper
roleRef:
  kind: ClusterRole
  name: nodereaper
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: nodereaper
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nodereaper
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nodereaper
  namespace: kube-system
roleRef:
  kind: Role
  name: nodereaper
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: nodereaper
