---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodereaperd
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodereaperd
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - update
  - list
  - watch
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  - apps
  - batch
  resources:
  - pods
  - daemonsets
  - statefulsets
  - replicasets
  - job
  - cronjob
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodereaperd
roleRef:
  kind: ClusterRole
  name: nodereaperd
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: nodereaperd
    namespace: kube-system
